// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyTWWQJpQEO83krpZGStE9XXVuvt95ac',
    appId: '1:1066299745958:web:506d28dda530101707f667',
    messagingSenderId: '1066299745958',
    projectId: 'eventplanner-86f6d',
    authDomain: 'eventplanner-86f6d.firebaseapp.com',
    storageBucket: 'eventplanner-86f6d.appspot.com',
    measurementId: 'G-KMF73CBS2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0QYBbJWLyLnCcGu0VT1iP9b30p1UjUxc',
    appId: '1:1066299745958:android:0c498f7780d4f41507f667',
    messagingSenderId: '1066299745958',
    projectId: 'eventplanner-86f6d',
    storageBucket: 'eventplanner-86f6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj66X66OJMmmY7PeoAaZD6Circ7xq8-7k',
    appId: '1:1066299745958:ios:599038969a4fd09f07f667',
    messagingSenderId: '1066299745958',
    projectId: 'eventplanner-86f6d',
    storageBucket: 'eventplanner-86f6d.appspot.com',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj66X66OJMmmY7PeoAaZD6Circ7xq8-7k',
    appId: '1:1066299745958:ios:4413afabe95f257407f667',
    messagingSenderId: '1066299745958',
    projectId: 'eventplanner-86f6d',
    storageBucket: 'eventplanner-86f6d.appspot.com',
    iosBundleId: 'com.example.eventPlanner.RunnerTests',
  );
}
